services:
  # Development backend
  backend-dev:
    build:
      context: ./backend
      dockerfile: DockerFile
    container_name: daemon_backend_dev
    ports:
      - "8000:8000"
    environment:
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173
      - DEBUG=true
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
    networks:
      - app-network-dev
    command: ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    restart: unless-stopped

  # Development frontend
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: daemon_frontend_dev
    ports:
      - "5173:5173"
    depends_on:
      - backend-dev
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network-dev
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    restart: unless-stopped

networks:
  app-network-dev:
    driver: bridge
